# Generated by Django 4.2.7 on 2023-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_userbookrelation_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="discount",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=4),
        ),
    ]
