# Generated by Django 4.2.7 on 2023-11-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_userbookrelation_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbookrelation",
            name="discount",
        ),
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=4),
        ),
    ]
