# Generated by Django 4.2.7 on 2023-11-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anime", "0002_anime_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnimeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.BooleanField(default=False)),
                ("in_bookmarks", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="anime.anime"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("edited", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "rate",
                    models.SmallIntegerField(
                        choices=[
                            (1, "It couldn't be worse!"),
                            (2, "Horrible"),
                            (3, "Very bad"),
                            (4, "Bad but not very"),
                            (5, "Ok"),
                            (6, "Nice, but could be better"),
                            (7, "Good"),
                            (8, "Very good"),
                            (9, "Incredible"),
                            (10, "Divine"),
                        ]
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="anime.anime"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
