# Generated by Django 4.2.7 on 2023-11-29 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anime", "0003_useranimerelation_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="reviews",
            field=models.ManyToManyField(
                related_name="reviews",
                through="anime.Review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="anime",
            name="watchers",
            field=models.ManyToManyField(
                related_name="watchers",
                through="anime.UserAnimeRelation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
