# Generated by Django 4.2.7 on 2023-11-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0004_anime_reviews_anime_watchers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="edited",
            field=models.DateTimeField(null=True),
        ),
    ]
