# Generated by Django 4.2.7 on 2023-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0005_alter_review_created_alter_review_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.SmallIntegerField(
                choices=[
                    (1, "It couldn't be worse!"),
                    (2, "Horrible"),
                    (3, "Very bad"),
                    (4, "Bad but not very"),
                    (5, "Ok"),
                    (6, "Nice, but could be better"),
                    (7, "Good"),
                    (8, "Very good"),
                    (9, "Incredible"),
                    (10, "Divine"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
